# ────────────────────────────────────────────────────────────────
#  all_zones_baseline.yaml - ABLATED BASELINE VERSION
# ────────────────────────────────────────────────────────────────
common:
  # REMOVED: patterns_excel - no pattern analysis needed for baseline
  # patterns_excel: patterns.xlsx  

  # ───────── Sliding-window parameters (UNCHANGED) ─────────
  window_length: 192
  stride: 1
  horizon: 1

  # ───────── Base LSTM architecture (UNCHANGED) ─────────
  model:
    lstm_layers: 2        # KEPT SAME: 2 layers as original
    lstm_units: 64        # KEPT SAME: 64 units as original
    dense_units: 32       # KEPT SAME: 32 units as original
    batch_size: 256       # KEPT SAME
    epochs: 20            # KEPT SAME: 20 epochs as original
    lr: 0.001            # KEPT SAME

  # REMOVED: Imbalance handling - using basic MSE instead
  # imbalance:
  #   focal_gamma: 2.0
  #   class_weight_zero: 1.0
  #   class_weight_nonzero: 0.0

  # ───────── Loss selector ─────────
  loss: mse              # ABLATED BASELINE: Only basic MSE, no focal/huber/pinball

  # REMOVED: Early stopping - train for fixed epochs
  # early_stopping:
  #   patience: 4
  #   min_delta: 0.001

  # REMOVED: Pattern alignment - no post-processing alignment
  # pattern_alignment:
  #   enabled: true
  #   iterations: 3
  #   clip_min: 0.5
  #   clip_max: 2.0

  # REMOVED: Autoregressive noise - deterministic predictions only
  # autoregressive:
  #   feedback_noise_std: 0.02

  # ───────── Federated setup (ABLATED BASELINE) ─────────
  federated:
    rounds: 5             # KEPT SAME: 5 rounds as original
    # REMOVED: FedProx parameters (mu_base, mu_min, mu_max)
    # Using simple FedAvg instead of FedProx
    # mu_base: 0.01
    # mu_min: 0.005
    # mu_max: 0.05

zones:
  # ABLATED BASELINE: All zones use same basic configuration
  # REMOVED: Zone-specific hyperparameters and loss functions
  Accueil:
    input_excel: Accueil_dataset.xlsx

  BTIC_Office:
    input_excel: BTIC_Office_dataset.xlsx

  Casablanca:
    input_excel: Casablanca_dataset.xlsx
    # REMOVED: Custom epochs and huber loss
    # model:
    #   epochs: 35
    # loss: huber

  Discovery:
    input_excel: Discovery_dataset.xlsx

  Experience:
    input_excel: Experience_dataset.xlsx

  Regie:
    input_excel: Regie_dataset.xlsx
    # REMOVED: Custom batch_size and pinball loss
    # model:
    #   batch_size: 512
    # loss: pinball
    # pinball_tau: 0.9

  Team_Office:
    input_excel: Team_Office_dataset.xlsx

  Tech_Area:
    input_excel: Tech_Area_dataset.xlsx
    # REMOVED: Custom learning rate and epochs
    # model:
    #   lr: 0.0005
    #   epochs: 30
